runs-on:
      - self-hosted
      - macOS
      - ARM64
      - tanweideMacBook-Air
steps:
      - name: Verify Machine Name
        run: |
          hostname
          whoami
      - name: Checkout repository
        uses: actions/checkout@v4
